Json config update
Unity-Technologies/com.unity.perception pull request #202
Opened 2021-02-11 01:33 UTC by sleal-unity

# Peer Review Information:
This PR updates scenario JSON serialization for DSaaS compatibility. This mainly includes adding support for string, decimal, and boolean scalar values to serialized randomizers and parameters.

## Editor / Package versioning:
**Editor Version Target (i.e. 19.3, 20.1)**: 2019.3

## Dev Testing:
**Tests Added**: 
Updated scenario tests to new format.

## Checklist
- [X] - Updated changelog

2021-02-11 17:10 UTC, mkamalza requested changes
Great work!

2021-02-11 18:09 UTC, sleal-unity commented on com.unity.perception/Runtime/Randomization/Scenarios/Scenario.cs
>          public override void DeserializeFromJson(string json)
Good catch, I'm axing this.

2021-02-11 18:10 UTC, sleal-unity commented on com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs
> +                Debug.Log($"No configuration file found at {defaultConfigFilePath}");
fixed

2021-02-11 18:26 UTC, sleal-unity commented on com.unity.perception/Runtime/Randomization/Scenarios/ScenarioBase.cs
> +                Debug.Log($"Deserialized scenario configuration from <a href=\"file:///${configFilePath}\">{configFilePath}</a>. " +
Moved this logging code under the actual serialization as suggested

2021-02-12 01:40 UTC, sleal-unity commented on com.unity.perception/Runtime/Randomization/Scenarios/Serialization/ScenarioSerializer.cs
> +            var jsonData = JObject.Parse(json);
Addressed in latest update

2021-02-12 20:02 UTC, mkamalza approved these changes
🟢

2021-02-19 18:24 UTC, merged