Visualizer
Unity-Technologies/com.unity.perception pull request #361
Opened 2021-08-13 16:12 UTC by leopoldo-zugasti

# Peer Review Information:

## Editor / Package versioning:
**Editor Version Target**: 2019.4

## Dev Testing:
**Tests Added**: 

**Core Scenario Tested**: 

**At Risk Areas**: 

## Checklist
- [ ] - Updated docs
- [ ] - Updated changelog
- [ ] - Updated test rail

2021-08-18 22:09 UTC, mkamalza requested changes
Great work. 
Many of my comments are suggestions for text changes.

2021-08-18 22:09 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                    if (netStatExitStatus != "0")
If this happens, we should not continue executing this method right? 
Also, what is the best course of action for the user? Is it possible to make the log more informative?

2021-08-18 22:09 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                                    Debug.LogError("Could not convert the following NetStat row to a Process to Port mapping.");
```suggestion
                                    Debug.LogError("Could not convert the following NetStat row to a process to port mapping.");
```

2021-08-18 22:09 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                                Debug.LogError("Unrecognized NetStat row to a Process to Port mapping.");
```suggestion
                                Debug.LogError("Could not convert the following NetStat row to a process to port mapping.");
```

2021-08-18 22:09 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                                        Debug.LogError("Could not convert the following NetStat row to a Process to Port mapping.");
```suggestion
                                        Debug.LogError("Could not convert the following NetStat row to a process to port mapping.");
```

2021-08-18 22:09 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                Debug.LogError("Could not list pip packages");
```suggestion
                Debug.LogError("Could not list pip packages to check whether the visualizer is installed. Cancelling update check");
```

2021-08-18 22:12 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        /// - installs virtualenv if it is not already installed
Nope

2021-08-18 22:13 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        static class ProcessPorts
Yeah that makes sense, would you like me to implement this or leave it in the backlog?

2021-08-18 22:18 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        static void CheckForUpdates()
Oh that's cool!

2021-08-18 22:41 UTC, mkamalza commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        static class ProcessPorts
Depends on how long you think it will take. If it is out of scope, leave it in the backlog.

2021-08-19 16:16 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        class ProcessPort
Yeah that makes a lot of sense

2021-08-19 16:35 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                if (EditorUtility.DisplayDialog("Kill visualizer?",
haha okay, yeah that's better

2021-08-19 16:57 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                //When launching the process it will try to open a new tab in the default browser, however if a tab for it already exists it will not
Yes and no, I've been going back and forth as to whether or not to keep it, what do you think?

2021-08-19 16:57 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +                //When launching the process it will try to open a new tab in the default browser, however if a tab for it already exists it will not
It's to handle the "double tabs open" issue

2021-08-19 17:13 UTC, leopoldo-zugasti commented on com.unity.perception/Editor/Visualizer/VisualizerInstaller.cs
> +        static bool ProcessAlive(int pythonPid, int port, int visualizerPid)
Great point I'll investigate

2021-08-23 17:17 UTC, mkamalza approved these changes

2021-08-23 17:18 UTC, merged